backend:
  name: git-gateway
  branch: main

media_folder: "IMAGENES"
public_folder: "IMAGENES"

collections:
  - name: "catalogo"
    label: "Catálogo Principal"
    files:
      - label: "Computadoras y Mini PCs"
        name: "computadoras"
        file: "_datos/computadoras.json"
        fields:
          - name: "productos"
            label: "Lista de Equipos"
            widget: "list"
            fields:
              - {label: "Título del Producto", name: "title", widget: "string"}
              - {label: "Precio", name: "precio", widget: "string"}
              - {label: "Imagen", name: "imagen", widget: "image"}
              - {label: "Descripción", name: "body", widget: "markdown"}
              - {label: "Agotado", name: "agotado", widget: "boolean", default: false}